version 0.38.8

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -618,6 +618,9 @@ LIBOBJS
 DEFINES
 PKG_LIBS
 PKG_CPPFLAGS
+OIDN_LIBS
+OIDN_LDFLAGS
+OIDN_CPPFLAGS
 CXXCPP
 XMKMF
 ac_ct_CXX
@@ -2501,14 +2504,12 @@ if test -z "${R_HOME}"; then
   exit 1
 fi
 
-##Fix CRAN note about looking for gcc
 CC=`"${R_HOME}/bin/R" CMD config CC`
 CFLAGS=`"${R_HOME}/bin/R" CMD config CFLAGS`
 CPPFLAGS=`"${R_HOME}/bin/R" CMD config CPPFLAGS`
 
 if test `uname` = "Darwin" ; then
   darwin="yes"
-  ## we want the *build* cputype and not the host one.
   cmd=`echo $CC $CFLAGS | grep -E 'x86_64|ppc64|-m64'`
   if test -n "$cmd"; then
     have_64bit="yes"
@@ -2519,8 +2520,8 @@ else
   darwin="no"
 fi
 
-CXX=`"${R_HOME}/bin/R" CMD config CXX17`
-CXXFLAGS=`"${R_HOME}/bin/R" CMD config CXX17FLAGS`
+CXX=`"${R_HOME}/bin/R" CMD config CXX20`
+CXXFLAGS=`"${R_HOME}/bin/R" CMD config CXX20FLAGS`
 CPPFLAGS=`"${R_HOME}/bin/R" CMD config CPPFLAGS`
 DEFINES="-D RAY_REPRODUCE_PERLIN -DSTRICT_R_HEADERS"
 
@@ -4410,12 +4411,211 @@ else
   fi
 fi
 
+{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for Open Image Denoise (OIDN)" >&5
+printf %s "checking for Open Image Denoise (OIDN)... " >&6; }
+
+OIDN_CPPFLAGS=""
+OIDN_LDFLAGS=""
+OIDN_LIBS=""
+
+if test -d "$OIDN_PATH"; then
+  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: found at $OIDN_PATH" >&5
+printf "%s\n" "found at $OIDN_PATH" >&6; }
+  OIDN_CPPFLAGS="-I'$OIDN_PATH/include'"
+  OIDN_LDFLAGS="-L$OIDN_PATH/lib"
+  OIDN_LIBS="-lOpenImageDenoise -ltbb"
+  DEFINES="${DEFINES} -DHAS_OIDN"
+  OIDN_LDFLAGS="${OIDN_LDFLAGS} -Wl,-rpath,$OIDN_PATH/lib"
+else
+  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: WARNING: OIDN not found. Skipping OIDN support." >&5
+printf "%s\n" "$as_me: WARNING: OIDN not found. Skipping OIDN support." >&2;}
+  OIDN_CPPFLAGS=""
+  OIDN_LDFLAGS=""
+  OIDN_LIBS=""
+fi
 
 
-# Write the flags into the src/Makevars file.
-PKG_CPPFLAGS="${PKG_CPPFLAGS}"
 
-PKG_LIBS="${LIBS} ${PKG_LIBS}"
+
+
+# Check for SSE/NEON support
+{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for SSE4.1 support" >&5
+printf %s "checking for SSE4.1 support... " >&6; }
+cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+
+    #include <smmintrin.h>
+
+int
+main (void)
+{
+
+    __m128 test = _mm_dp_ps(_mm_set1_ps(1.0f), _mm_set1_ps(2.0f), 0xFF);
+
+  ;
+  return 0;
+}
+_ACEOF
+if ac_fn_cxx_try_compile "$LINENO"
+then :
+  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+printf "%s\n" "yes" >&6; }
+   DEFINES="${DEFINES} -DHAS_SSE -DHAS_SSE41 -DRAYSIMD -DRAYSIMDVECOFF"
+   CXXFLAGS="${CXXFLAGS} -msse4.1"
+
+else $as_nop
+  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: no" >&5
+printf "%s\n" "no" >&6; }
+
+   # If SSE4.1 not found, check SSE3
+   { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for SSE3 support" >&5
+printf %s "checking for SSE3 support... " >&6; }
+   cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+
+       #include <pmmintrin.h>
+
+int
+main (void)
+{
+
+       __m128 test = _mm_hadd_ps(_mm_set1_ps(1.0f), _mm_set1_ps(1.0f));
+
+  ;
+  return 0;
+}
+_ACEOF
+if ac_fn_cxx_try_compile "$LINENO"
+then :
+  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+printf "%s\n" "yes" >&6; }
+      DEFINES="${DEFINES} -DHAS_SSE -DHAS_SSE3 -DRAYSIMD -DRAYSIMDVECOFF"
+      CXXFLAGS="${CXXFLAGS} -msse3"
+
+else $as_nop
+  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: no" >&5
+printf "%s\n" "no" >&6; }
+
+      # If SSE3 not found, fall back to SSE2
+      { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for SSE2 support" >&5
+printf %s "checking for SSE2 support... " >&6; }
+      cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+
+          #include <emmintrin.h>
+
+int
+main (void)
+{
+
+          __m128d test = _mm_setzero_pd();
+
+  ;
+  return 0;
+}
+_ACEOF
+if ac_fn_cxx_try_compile "$LINENO"
+then :
+  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+printf "%s\n" "yes" >&6; }
+         DEFINES="${DEFINES} -DHAS_SSE -DHAS_SSE2 -DRAYSIMD -DRAYSIMDVECOFF"
+         CXXFLAGS="${CXXFLAGS} -msse2"
+
+else $as_nop
+  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: no" >&5
+printf "%s\n" "no" >&6; }
+         # If SSE2 not found, try SSE or nothing
+         { printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for SSE support" >&5
+printf %s "checking for SSE support... " >&6; }
+         cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+
+             #include <xmmintrin.h>
+
+int
+main (void)
+{
+
+             __m128 test = _mm_setzero_ps();
+
+  ;
+  return 0;
+}
+_ACEOF
+if ac_fn_cxx_try_compile "$LINENO"
+then :
+  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+printf "%s\n" "yes" >&6; }
+            DEFINES="${DEFINES} -DHAS_SSE -DRAYSIMD -DRAYSIMDVECOFF"
+            CXXFLAGS="${CXXFLAGS} -msse"
+
+else $as_nop
+  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: no" >&5
+printf "%s\n" "no" >&6; }
+            # SSE not found at all; no vector intrinsics
+
+fi
+rm -f core conftest.err conftest.$ac_objext conftest.beam conftest.$ac_ext
+
+fi
+rm -f core conftest.err conftest.$ac_objext conftest.beam conftest.$ac_ext
+
+fi
+rm -f core conftest.err conftest.$ac_objext conftest.beam conftest.$ac_ext
+
+fi
+rm -f core conftest.err conftest.$ac_objext conftest.beam conftest.$ac_ext
+
+{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking for NEON support" >&5
+printf %s "checking for NEON support... " >&6; }
+cat confdefs.h - <<_ACEOF >conftest.$ac_ext
+/* end confdefs.h.  */
+
+#if defined(__ARM_NEON) || defined(__ARM_NEON__)
+#include <arm_neon.h>
+#endif
+
+int
+main (void)
+{
+float32x4_t test = vdupq_n_f32(0.0);
+  ;
+  return 0;
+}
+_ACEOF
+if ac_fn_cxx_try_compile "$LINENO"
+then :
+  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: yes" >&5
+printf "%s\n" "yes" >&6; }
+   DEFINES="${DEFINES} -DHAS_NEON -DRAYSIMD -DRAYSIMDVECOFF"
+   if test "$darwin" = "yes"; then
+     CXXFLAGS="${CXXFLAGS} -march=armv8-a+simd"
+   else
+     CXXFLAGS="${CXXFLAGS} -mfpu=neon"
+   fi
+else $as_nop
+  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: no" >&5
+printf "%s\n" "no" >&6; }
+fi
+rm -f core conftest.err conftest.$ac_objext conftest.beam conftest.$ac_ext
+
+{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: checking If test debugging should be turned on:" >&5
+printf %s "checking If test debugging should be turned on:... " >&6; }
+{ printf "%s\n" "$as_me:${as_lineno-$LINENO}: RAY_COLOR_DEBUG is \"$RAY_COLOR_DEBUG\"" >&5
+printf "%s\n" "$as_me: RAY_COLOR_DEBUG is \"$RAY_COLOR_DEBUG\"" >&6;}
+
+if test "$RAY_COLOR_DEBUG" = "true"; then
+  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: Yes, enabling debug" >&5
+printf "%s\n" "Yes, enabling debug" >&6; }
+  DEFINES="${DEFINES} -DRAY_COLOR_DEBUG"
+else
+  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: result: No, not enabling debug" >&5
+printf "%s\n" "No, not enabling debug" >&6; }
+fi
+
+PKG_CPPFLAGS="${PKG_CPPFLAGS} ${OIDN_CPPFLAGS}"
+
+PKG_LIBS="${LIBS} ${PKG_LIBS} ${OIDN_LDFLAGS} ${OIDN_LIBS}"
 
 DEFINES="${DEFINES}"
 
@@ -5580,6 +5780,8 @@ echo "
     cppflags: ${CPPFLAGS} ${DEFINES}
     libs:     ${PKG_LIBS}
     includes: ${PKG_CPPFLAGS}
+    cxxflags: ${CXXFLAGS}
 
   --------------------------------------------------
 "
+
